[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources
[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap
[[ -f ~/.xbindkeysrc ]] && xbindkeys

feh --bg-scale /home/worace/dotfiles/wallpaper/goat.jpg

xset -b
# xset r rate <delay ms> <speed hz>
xset r rate 220 50

exec i3
