# -*- mode: snippet; require-final-newline: nil -*-
# name: Rakefile
# key:
# binding: direct-keybinding
# --

require "rake"
require "rake/testtask"

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/*_test.rb']
  t.verbose = true
end

task default: :test